# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  identifier = "resume"
  name = "About Us"
  url = "nosotros/"
  weight = 10

[[main]]
  identifier = "resume1"
  name = "Background"
  url = "trayectoria/"
  parent = "resume"
  weight = 15

[[main]]
  identifier = "resume2"
  name = "What We Do"
  url = "projects/"
  parent = "resume"
  weight = 20

[[main]]
  name = "Blog"
  url = "#posts"
  weight = 30

[[main]]
  name = "Publications"
  url = "publication/"
  weight = 40

[[main]]
  name = "Bioeconomy"
  url = "bioeconomia/"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 70
